[package]
name = "bike"
version = "0.1.0"
edition = "2024"

[dependencies]
btleplug = { version = "0.11", features = ["serde"] }
tokio = { version = "1", features = ["full"] }
futures = "0.3.31"
anyhow = "1.0.99"
uuid = "1.18.0"
